// <auto-generated />
using System;
using System.Collections.Generic;
using MSProfessionals.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSProfessionals.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501193221_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shc_professional")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSProfessionals.Domain.Entities.CountryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("PK_tb_country_codes");

                    b.ToTable("tb_country_codes", "shc_professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PK_tb_currencies");

                    b.ToTable("tb_currencies", "shc_professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PK_tb_languages");

                    b.ToTable("tb_languages", "shc_professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Dictionary<string, string>>("Media")
                        .HasColumnType("jsonb")
                        .HasColumnName("media");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PhoneCountryCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("phone_country_code_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<Guid>("PreferredLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_language_id");

                    b.Property<Dictionary<string, string>>("SocialMedia")
                        .HasColumnType("jsonb")
                        .HasColumnName("social_media");

                    b.Property<Guid>("TimezoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("timezone_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_tb_professionals");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("IX_tb_professionals_currency_id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneCountryCodeId")
                        .HasDatabaseName("IX_tb_professionals_phone_country_code_id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("PreferredLanguageId")
                        .HasDatabaseName("IX_tb_professionals_preferred_language_id");

                    b.HasIndex("TimezoneId")
                        .HasDatabaseName("IX_tb_professionals_timezone_id");

                    b.ToTable("tb_professionals", "shc_professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.ProfessionalAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("city");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postalcode");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street_address");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_tb_professional_address");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_tb_professional_address_country_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("IX_tb_professional_address_professional_id");

                    b.ToTable("tb_professional_address", "shc_professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.TimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_tb_time_zones");

                    b.ToTable("tb_time_zones", "shc_professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.Professional", b =>
                {
                    b.HasOne("MSProfessionals.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tb_professionals_tb_currencies_currency_id");

                    b.HasOne("MSProfessionals.Domain.Entities.CountryCode", "PhoneCountryCode")
                        .WithMany()
                        .HasForeignKey("PhoneCountryCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tb_professionals_tb_country_codes_phone_country_code_id");

                    b.HasOne("MSProfessionals.Domain.Entities.Language", "PreferredLanguage")
                        .WithMany()
                        .HasForeignKey("PreferredLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tb_professionals_tb_languages_preferred_language_id");

                    b.HasOne("MSProfessionals.Domain.Entities.TimeZone", "Timezone")
                        .WithMany()
                        .HasForeignKey("TimezoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tb_professionals_tb_time_zones_timezone_id");

                    b.Navigation("Currency");

                    b.Navigation("PhoneCountryCode");

                    b.Navigation("PreferredLanguage");

                    b.Navigation("Timezone");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.ProfessionalAddress", b =>
                {
                    b.HasOne("MSProfessionals.Domain.Entities.CountryCode", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tb_professional_address_tb_country_codes_country_id");

                    b.HasOne("MSProfessionals.Domain.Entities.Professional", "Professional")
                        .WithMany("Addresses")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tb_professional_address_tb_professionals_professional_id");

                    b.Navigation("Country");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("MSProfessionals.Domain.Entities.Professional", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
