apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: default
type: Opaque
data:
  host: MTkyLjE2OC4xMDAuMTc=  # 192.168.100.17 em base64
  port: NTQzMg==              # 5432 em base64
  database: bXNfcHJvZmVzc2lvbmFscw==  # ms_professionals em base64
  username: ZWFzeXByb2ZpbmQ=  # easyprofind em base64
  password: TWFzdGVyQDEyMw==  # Master@123 em base64 