apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-plugin
  namespace: default
plugin: request-transformer
config:
  add:
    headers:
    - 'X-Forwarded-Proto: http'
    - 'X-Forwarded-Host: ms-profissionais.local'
    - 'X-Forwarded-Port: 80'
    - 'X-Real-IP: 127.0.0.1'
  remove:
    headers: []
  replace:
    headers: []
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin
  namespace: default
plugin: cors
config:
  credentials: true
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - Authorization
  - X-Requested-With
  max_age: 3600
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  origins:
  - '*' 