apiVersion: v1
kind: Service
metadata:
  name: ms-professionals-service
  namespace: default
spec:
  selector:
    app: ms-professionals
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 