apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-professionals
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-professionals
  template:
    metadata:
      labels:
        app: ms-professionals
    spec:
      containers:
      - name: ms-professionals
        image: ms-professionals:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_HOST
          value: "localhost"
        - name: DatabaseSettings__Host
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host
        - name: DatabaseSettings__Port
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: port
        - name: DatabaseSettings__Database
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database
        - name: DatabaseSettings__Username
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: DatabaseSettings__Password
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: connection-string
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3 