apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-profissionais
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-profissionais
  template:
    metadata:
      labels:
        app: ms-profissionais
    spec:
      containers:
      - name: ms-profissionais
        image: ms-profissionais:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: connection-string
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 