apiVersion: v1
kind: Service
metadata:
  name: ms-professionals-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ms-professionals
  type: LoadBalancer 